'use strict';
document.documentElement.classList.add('js');
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
let paused=motionQuery.matches;
const pauseButton=document.querySelector('#motion-toggle');
function syncMotion(){document.body.classList.toggle('motion-paused',paused);pauseButton.textContent=paused?'Play animation ▷':'Pause animation Ⅱ';pauseButton.setAttribute('aria-pressed',String(paused));}
pauseButton.addEventListener('click',()=>{paused=!paused;syncMotion();});motionQuery.addEventListener('change',e=>{paused=e.matches;syncMotion();});syncMotion();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelector('#year').textContent=new Date().getFullYear();function clock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit'});}clock();setInterval(clock,60000);
let active=0;const cards=[...document.querySelectorAll('[data-project]')];function renderProjects(){cards.forEach((card,i)=>{card.dataset.position=i===active?'active':i===(active+1)%3?'right':'left';});document.querySelector('#project-position').textContent=`0${active+1} / 03`;}
document.querySelector('#prev-project').addEventListener('click',()=>{active=(active+2)%3;renderProjects();});document.querySelector('#next-project').addEventListener('click',()=>{active=(active+1)%3;renderProjects();});renderProjects();
const services=['SEO','Web Development'];const cart=new Set();try{const saved=JSON.parse(localStorage.getItem('rizwan-services')||'[]');if(Array.isArray(saved))saved.filter(x=>services.includes(x)).forEach(x=>cart.add(x));}catch{}
const dialog=document.querySelector('#cart-dialog');const items=document.querySelector('#cart-items');let lastFocus;function closeCart(){dialog.close();document.body.style.overflow='';lastFocus?.focus();}function openCart(){lastFocus=document.activeElement;dialog.showModal();document.body.style.overflow='hidden';}document.querySelectorAll('[data-open-cart]').forEach(b=>b.addEventListener('click',openCart));document.querySelector('#close-cart').addEventListener('click',closeCart);dialog.addEventListener('cancel',e=>{e.preventDefault();closeCart();});dialog.addEventListener('click',e=>{if(e.target===dialog&&e.clientX<dialog.getBoundingClientRect().left)closeCart();});
function renderCart(){try{localStorage.setItem('rizwan-services',JSON.stringify([...cart]));}catch{}document.querySelectorAll('[data-count]').forEach(n=>n.textContent=cart.size);items.replaceChildren();if(!cart.size){const p=document.createElement('p');p.className='empty-cart';p.textContent='Your brief is empty. Select SEO, Web Development or both to get started.';items.append(p);const b=document.createElement('button');b.className='pill dark';b.textContent='Choose services';b.onclick=()=>{closeCart();document.querySelector('#services').scrollIntoView({behavior:paused?'instant':'smooth'});};items.append(b);}for(const service of cart){const row=document.createElement('div');row.className='cart-item';const name=document.createElement('strong');name.textContent=service;const remove=document.createElement('button');remove.textContent='Remove';remove.setAttribute('aria-label',`Remove ${service}`);remove.onclick=()=>{cart.delete(service);renderCart();};row.append(name,remove);items.append(row);}document.querySelector('#checkout').disabled=!cart.size;document.querySelectorAll('[data-service]').forEach(b=>{const selected=cart.has(b.dataset.service);b.innerHTML=selected?'Added to brief <span>✓</span>':'Add to brief <span>+</span>';b.setAttribute('aria-pressed',String(selected));});}
let toastTimer;document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>{if(cart.has(b.dataset.service)){openCart();return;}cart.add(b.dataset.service);renderCart();const toast=document.querySelector('#toast');toast.textContent=`${b.dataset.service} added — open “Your brief” to checkout.`;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),3500);}));renderCart();
function buildWhatsAppUrl(selected,name,website,brief){const message=['Hello Rizwan, I would like to request the following services:',...selected.map(s=>`• ${s}`),name?`\nName: ${name}`:'',website?`Website: ${website}`:'',brief?`\nProject brief: ${brief}`:'','\nPlease let me know the next steps and a quote.'].filter(Boolean).join('\n');return 'https://wa.me/447404303928?text='+encodeURIComponent(message);}
document.querySelector('#checkout-form').addEventListener('submit',e=>{e.preventDefault();if(!cart.size)return;const data=new FormData(e.currentTarget);const url=buildWhatsAppUrl([...cart],data.get('name').trim(),data.get('website').trim(),data.get('brief').trim());window.open(url,'_blank','noopener,noreferrer');});
// Scroll choreography: portrait depth, word illumination and staggered paper travel.
const portrait=document.querySelector('.about-portrait');const aboutSection=document.querySelector('.about-scroll');const sky=document.querySelector('.sky-layer');const skyHero=document.querySelector('.hero');const papers=[...document.querySelectorAll('.floating-paper')];const sentence=document.querySelector('.word-reveal');const words=sentence.textContent.trim().split(/\s+/);sentence.setAttribute('aria-label',sentence.textContent);sentence.replaceChildren(...words.flatMap(word=>{const span=document.createElement('span');span.textContent=word;span.setAttribute('aria-hidden','true');return [span,document.createTextNode(' ')];}));const wordSpans=[...sentence.querySelectorAll('span')];
const orbit=document.querySelector('.orbit div');const orbitWords=['AI RESEARCH','WEB DEVELOPMENT','SEO','PYTHON','EXPLAINABILITY','DIGITAL IDEAS'];orbit.replaceChildren(...orbitWords.map((text,i)=>{const span=document.createElement('span');span.textContent=text;span.style.transform=`rotate(${i*60}deg)`;return span;}));
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));let scrollQueued=false;
function choreograph(){scrollQueued=false;const vh=innerHeight;const mobile=innerWidth<=800;const r=aboutSection.getBoundingClientRect();const progress=clamp(-r.top/Math.max(1,r.height-vh));const wordProgress=mobile?clamp((vh*.7-sentence.getBoundingClientRect().top)/(vh*.45)):clamp(progress*1.8+.06);wordSpans.forEach((w,i)=>w.style.opacity=paused?'1':String(clamp((wordProgress-i/wordSpans.length)*wordSpans.length,.3,1)));portrait.style.transform=paused||mobile?'none':`scale(${1.08-progress*.08}) translateY(${progress*25}px)`;const hr=skyHero.getBoundingClientRect();sky.style.transform=paused?'none':`translateY(${clamp(-hr.top,0,vh)*.18}px) scale(1.04)`;papers.forEach((paper,i)=>{const top=paper.offsetTop+paper.offsetParent.offsetTop-scrollY;const travel=clamp((vh-top)/vh,-1,1);paper.style.transform=paused||mobile?'none':`translateY(${-travel*(i?65:100)}px) rotate(${i?3:-3}deg)`;});}
function queueScroll(){if(!scrollQueued){scrollQueued=true;requestAnimationFrame(choreograph);}}addEventListener('scroll',queueScroll,{passive:true});addEventListener('resize',queueScroll);pauseButton.addEventListener('click',queueScroll);motionQuery.addEventListener('change',queueScroll);choreograph();
let touchStart=null;const stage=document.querySelector('.project-stage');stage.addEventListener('touchstart',e=>{touchStart=e.touches[0].clientX;},{passive:true});stage.addEventListener('touchend',e=>{if(touchStart===null)return;const delta=e.changedTouches[0].clientX-touchStart;if(Math.abs(delta)>60){active=(active+(delta<0?1:2))%3;renderProjects();}touchStart=null;},{passive:true});
